name: location_map_app
description: A Flutter application to display a location on a map.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^2.2.0  # Check for the latest version on pub.dev
  geocoding: ^2.2.1  # For converting addresses into coordinates
  google_maps_flutter: ^2.9.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
